/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorAnimal;
import javax.swing.JFrame;

/**
 *
 * @author Dante
 */
public class Modificar_Animal extends javax.swing.JDialog {
    private ControladorAnimal refControladorAnimal;
    /**
     * Creates new form Modificar_Animal
     */
    public Modificar_Animal(java.awt.Frame parent, boolean modal,String Raza, String Nombre, String Edad) {        //Preparo el constructor sobrecargado con los datos que quiero que se enseñen luego en los campos TXT al abrir el JDialog
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        refControladorAnimal = new ControladorAnimal();         //Seteamos a los campos TXT de este mismo JDialog los parametros recividos arriba en el constructor
        txtModificar_nombre.setText(Nombre);
        txtModificar_raza.setText(Raza);
        txtModificar_edad.setText(Edad);
    }

    private Modificar_Animal(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModificar_Titulo = new javax.swing.JLabel();
        lblModificar_id = new javax.swing.JLabel();
        lblModificar_raza = new javax.swing.JLabel();
        lblModificar_nombre = new javax.swing.JLabel();
        lblModificar_edad = new javax.swing.JLabel();
        txtModificar_id = new javax.swing.JTextField();
        txtModificar_raza = new javax.swing.JTextField();
        txtModificar_nombre = new javax.swing.JTextField();
        txtModificar_edad = new javax.swing.JTextField();
        btnModificar_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModificar_Titulo.setText("Modificar Animal");

        lblModificar_id.setText("ID");

        lblModificar_raza.setText("Raza");

        lblModificar_nombre.setText("Nombre");

        lblModificar_edad.setText("Edad");

        txtModificar_id.setEditable(false);

        txtModificar_raza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificar_razaActionPerformed(evt);
            }
        });

        btnModificar_guardar.setText("Guardar");
        btnModificar_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModificar_id)
                            .addComponent(lblModificar_edad)
                            .addComponent(lblModificar_nombre)
                            .addComponent(lblModificar_raza))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModificar_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificar_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificar_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnModificar_guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblModificar_Titulo)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModificar_Titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar_id)
                    .addComponent(txtModificar_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar_raza)
                    .addComponent(txtModificar_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar_nombre)
                    .addComponent(txtModificar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar_edad)
                    .addComponent(txtModificar_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnModificar_guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModificar_razaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificar_razaActionPerformed
        // TODO add your handling code here:
        
               
    }//GEN-LAST:event_txtModificar_razaActionPerformed

    private void btnModificar_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_guardarActionPerformed
        // TODO add your handling code here:
        refControladorAnimal.modificarAnimal();
    }//GEN-LAST:event_btnModificar_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar_Animal dialog = new Modificar_Animal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar_guardar;
    private javax.swing.JLabel lblModificar_Titulo;
    private javax.swing.JLabel lblModificar_edad;
    private javax.swing.JLabel lblModificar_id;
    private javax.swing.JLabel lblModificar_nombre;
    private javax.swing.JLabel lblModificar_raza;
    private javax.swing.JTextField txtModificar_edad;
    private javax.swing.JTextField txtModificar_id;
    private javax.swing.JTextField txtModificar_nombre;
    private javax.swing.JTextField txtModificar_raza;
    // End of variables declaration//GEN-END:variables
}
